# Generated by Django 5.1.7 on 2025-04-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('bg_color', models.CharField(default='#000000', max_length=7)),
                ('button_color', models.CharField(default='#46336B', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('copyright_text', models.CharField(default='© 2025 AIEccoGRID', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='displayhotproductincategories',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='sliderarea',
            name='product_url',
        ),
    ]
