# Generated by Django 5.1.7 on 2025-04-04 17:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#343a40', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='footer',
            name='button_color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(default='© 2025 YourWebsite. All rights reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
