# Generated by Django 5.1.7 on 2025-04-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_footer_bg_color_alter_footer_button_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_link',
        ),
    ]
