# Generated by Django 5.1.7 on 2025-04-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_footer_bg_color_remove_footer_button_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
