# Generated by Django 4.2.5 on 2023-12-18 12:51

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField(auto_now_add=True)),
                ('oder_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CuponCodeGenaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cupon_code', models.CharField(max_length=50)),
                ('discoun_parcent', models.PositiveIntegerField()),
                ('up_to', models.PositiveIntegerField(help_text='Limit of Discount Amaount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zip_code', models.PositiveIntegerField()),
                ('street_address', models.CharField(max_length=250)),
                ('mobile', models.PositiveIntegerField()),
                ('is_billing', models.BooleanField(default=True)),
                ('is_shipping', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('regular_price', models.PositiveIntegerField()),
                ('stoc', models.PositiveIntegerField(default=10, verbose_name='Available in Stock')),
                ('out_of_stoc', models.BooleanField(default=False)),
                ('discounted_parcent', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField(max_length=2000)),
                ('modle', models.CharField(max_length=50)),
                ('tag', models.CharField(help_text='Enter your tag coma separated', max_length=50)),
                ('details_description', ckeditor.fields.RichTextField(help_text="Details product description display in the bottom of the product Page. It's help buyer to make deceion on your product", max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.categories')),
                ('vendor_stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vendors.vendorstore')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStarRatingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_message', models.CharField(max_length=1000)),
                ('review_images', models.ImageField(blank=True, upload_to='product-review-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=70)),
                ('details', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PlacedOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Oder Recived', 'Oder Recived'), ('Oder Packed', 'Oder Packed'), ('Oder OnTheWay', 'Oder OnTheWay'), ('Oder Shipped', 'Oder Shipped')], default='Oder Recived', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('placed_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=12, null=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='products.customeraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedeOderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('placed_oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.placedoder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('completed_oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_items', to='products.completedoder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='completedoder',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customeraddress'),
        ),
        migrations.AddField(
            model_name='completedoder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categories',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.industry'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cupon_applaied', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('cupon_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cuponcodegenaration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_with_product_in_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
