# Generated by Django 5.1.7 on 2025-03-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedoderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_product', to='products.product'),
        ),
    ]
